# Generated by Django 3.1.3 on 2021-11-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='sipnosis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
