# Generated by Django 3.1.3 on 2021-11-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioapp', '0002_libro_sipnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='sipnosis',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
