# Generated by Django 3.1.3 on 2021-12-09 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioapp', '0004_item_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='Libro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='biblioapp.libro'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
