# Generated by Django 3.1.3 on 2022-01-16 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioapp', '0005_auto_20211209_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='Libro',
            new_name='libro',
        ),
    ]
